'use client'

import { useCallback, useEffect, useRef, useState } from 'react'
import { ArrowDownLeft, ArrowUpRight, RefreshCw, Search } from 'lucide-react'
import { RouteGuard } from '@/components/route-guard'
import { api } from '@/lib/api-client'
import { formatDate, formatIDR } from '@/lib/format'

interface CashMovement {
  id: number
  movement_date: string
  amount: number
  direction: 'in' | 'out' | string
  trigger: string
  payment_method_id: number
  reference_type: string | null
  reference_id: number | null
  created_by: number
}

interface MovementResponse {
  data: CashMovement[]
  pagination: { page: number; per_page: number; total: number; total_pages: number }
}

function CashLedgerPage() {
  const [rows, setRows] = useState<CashMovement[]>([])
  const [balance, setBalance] = useState<number | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [query, setQuery] = useState('')
  const [page, setPage] = useState(1)
  const [totalPages, setTotalPages] = useState(1)
  const loadVersion = useRef(0)

  const load = useCallback(async () => {
    const version = ++loadVersion.current
    setLoading(true)
    setError('')
    try {
      const params: Record<string, string> = { page: String(page), per_page: '25', sort: '-id' }
      if (query.trim()) params.q = query.trim()
      const [ledger, cash] = await Promise.all([
        api.get<MovementResponse>('/cash-movements', { params }),
        api.get<{ balance: number }>('/cash-movements/balance'),
      ])
      if (version !== loadVersion.current) return
      setRows(ledger.data ?? [])
      setTotalPages(Math.max(1, ledger.pagination?.total_pages ?? 1))
      setBalance(Number(cash.balance) || 0)
    } catch (e) {
      if (version !== loadVersion.current) return
      setError(e instanceof Error ? e.message : 'Could not load the cash ledger.')
    } finally {
      if (version === loadVersion.current) setLoading(false)
    }
  }, [page, query])

  useEffect(() => { load() }, [load])

  return (
    <div className="content">
      <div className="page-heading">
        <div><div className="eyebrow">FINANCE / CASH</div><h1>Cash ledger</h1><p>Review the read-only record of cash received and paid out.</p></div>
        <button className="button button-secondary" onClick={load} disabled={loading}><RefreshCw size={15} /> Refresh</button>
      </div>
      <section className="metrics cash-metrics">
        <article className="metric-card"><div className="metric-label">Cash balance</div><div className="metric-value">{balance === null ? '—' : formatIDR(balance)}</div><div className="change-note">Current balance from the cash ledger</div></article>
        <article className="metric-card"><div className="metric-label">Entries on this page</div><div className="metric-value">{rows.length}</div><div className="change-note">Page {page} of {totalPages}</div></article>
      </section>
      <section className="panel">
        <div className="panel-header cash-panel-header"><div><h2>Cash movements</h2><p>Entries are generated by posted transactions and cannot be edited here.</p></div><label className="cash-search"><Search size={16} /><input value={query} onChange={(e) => { setQuery(e.target.value); setPage(1) }} placeholder="Search trigger or reference" /></label></div>
        {error && <div className="notice error">{error}</div>}
        <div className="sales-table-wrap"><table className="sales-table"><thead><tr><th>Date</th><th>Direction</th><th>Trigger</th><th>Reference</th><th className="sales-td-right">Amount</th></tr></thead><tbody>
          {loading ? <tr><td colSpan={5} className="empty">Loading cash movements…</td></tr> : rows.length === 0 ? <tr><td colSpan={5} className="empty">No cash movements found.</td></tr> : rows.map((row) => <tr key={row.id}><td>{formatDate(row.movement_date)}</td><td><span className={`cash-direction ${row.direction === 'in' ? 'incoming' : 'outgoing'}`}>{row.direction === 'in' ? <ArrowDownLeft size={14} /> : <ArrowUpRight size={14} />}{row.direction === 'in' ? 'In' : 'Out'}</span></td><td>{row.trigger.replace(/_/g, ' ')}</td><td>{row.reference_type ? `${row.reference_type.replace(/_/g, ' ')}${row.reference_id ? ` #${row.reference_id}` : ''}` : '—'}</td><td className="sales-td-right sales-num">{formatIDR(row.amount)}</td></tr>)}
        </tbody></table></div>
        <div className="sales-pagination"><span>Page {page} of {totalPages}</span><div className="sales-pagination-nav"><button className="sales-pager" disabled={page <= 1 || loading} onClick={() => setPage((p) => p - 1)}>Previous</button><button className="sales-pager" disabled={page >= totalPages || loading} onClick={() => setPage((p) => p + 1)}>Next</button></div></div>
      </section>
    </div>
  )
}

export default function CashRoute() {
  return <RouteGuard required="finance.view_cash"><CashLedgerPage /></RouteGuard>
}
